# Generated by Django 5.1.2 on 2024-11-02 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspect',
            options={'verbose_name': 'Аспект', 'verbose_name_plural': 'Аспекты'},
        ),
        migrations.AlterModelOptions(
            name='aspectsummary',
            options={'verbose_name': 'Вывод по аспекту', 'verbose_name_plural': 'Выводы по аспектам'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='generalsummary',
            options={'verbose_name': 'Общий вывод', 'verbose_name_plural': 'Общие выводы'},
        ),
        migrations.AlterModelOptions(
            name='reviewcreator',
            options={'verbose_name': 'Автор отзыва', 'verbose_name_plural': 'Авторы отзывов'},
        ),
        migrations.AddField(
            model_name='aspect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='aspectsummary',
            name='aspect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.aspect', verbose_name='Аспект'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspectsummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_self_review',
            field=models.BooleanField(default=False, verbose_name='Самооценка'),
        ),
        migrations.AddField(
            model_name='generalsummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='generalsummary',
            name='score',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Общая оценка'),
        ),
        migrations.AddField(
            model_name='reviewcreator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='aspect',
            name='text',
            field=models.TextField(verbose_name='Текст аспекта'),
        ),
        migrations.AlterField(
            model_name='aspectsummary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='aspectsummary',
            name='score',
            field=models.BigIntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='aspectsummary',
            name='text',
            field=models.TextField(verbose_name='Текст аспекта'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='review_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.reviewcreator', verbose_name='Автор отзыва'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='generalsummary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='generalsummary',
            name='text',
            field=models.TextField(verbose_name='Общий вывод'),
        ),
    ]
