# Generated by Django 5.1.2 on 2024-11-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_aspect_options_alter_aspectsummary_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspect',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aspectsummary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='generalsummary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reviewcreator',
            name='created_at',
        ),
    ]
