# Generated by Django 5.1.2 on 2024-11-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_aspect_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspectsummary',
            name='aspect',
        ),
        migrations.AddField(
            model_name='aspectsummary',
            name='aspect_name',
            field=models.CharField(default='Unnamed Aspect', max_length=255, verbose_name='Название аспекта'),
        ),
    ]
