# Generated by Django 5.1.2 on 2024-11-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_aspectsummary_aspect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspectsummary',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='Вес отзыва'),
        ),
    ]
