# Generated by Django 5.1.2 on 2024-11-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_aspectsummary_weight_feedback_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspectsummary',
            name='score',
            field=models.FloatField(verbose_name='Оценка'),
        ),
    ]
