# Generated by Django 5.1.2 on 2024-11-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_aspectsummary_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='psychotype',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Психотип'),
        ),
    ]
