# Generated by Django 5.1.2 on 2024-11-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_employee_psychotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsummary',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая оценка'),
        ),
    ]
